### ISSUE TITLE
remove/restart new scan

### ISSUE THREAD

**Issue by UserX404** [nunocunha/qr-coder#10]
after successfully generate QR from image, how is it possible to remove the QR and restart a new scan?
clicking anywhere or pushing esc doesn't bring the desired effect.

After reloading the whole page the item is removed from context menu.

**Comment by nunocunha** [comment]
Pushing Esc could be an enhancement, but I can't reproduce the issue you're having of not being able to re-generate QR codes. What browser are you using?

**Comment by UserX404** [comment]
it's quiet an old issue. I'm also not able to reproduce them.
