### ISSUE TITLE
Some pages on Firefox don't allow a QR code generation

### ISSUE THREAD

**Issue by nunocunha** [nunocunha/qr-coder#2]
It's most probably related to [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) on Firefox. The same problem does not occur on both Google Chrome and/or Microsoft Edge.

**Comment by ljani** [comment]
Just a headsup for everyone else coming here wondering why it didn't work on the very first page you tried, [MDN states that](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#WebExtension_APIs):
> Note that content scripts are currently blocked on **addons.mozilla.org**. If you try to inject a content script into a page in this domain, it will fail and the page will log a CSP error.

@nunocunha Do you have any other examples where the script doesn't work? Normal pages with CSP seem to be fine for me.

Thanks for the addon.

**Comment by nunocunha** [comment]
@ljani I have yet to encounter a website where it did not work, but I decided I should let people know I'm aware it doesn't work on some websites. Thanks for clearing that up about the AMO website, great piece of information!
