### ISSUE TITLE
Save QR Code as PNG/JPG

### ISSUE THREAD

**Issue by Riajyuu** [nunocunha/qr-coder#4]

**Comment by nunocunha** [comment]
Should be doable, although it'll be in GIF format and not PNG or JPG, so I don't have to add another library or do exotic stuff. I'm trying to keep this as simple as possible, both in code and UX.

**Comment by Riajyuu** [comment]
@nunocunha a little curious, why GIF indeed? Since it is only a static image.

**Comment by nunocunha** [comment]
@Rictusempra the library currently in use only supports SVG or GIF, and I'm using SVG because results in faster QR code generation. Since it's a monochromatic GIF (I believe), it'll still result in a small file.
